"""add edited_at and deleted to messages

Revision ID: 5ba3c7771db7
Revises: 7d9210412609
Create Date: 2026-05-07 18:26:05.967860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5ba3c7771db7'
down_revision: Union[str, None] = '7d9210412609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('messages', sa.Column('deleted', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'deleted')
    op.drop_column('messages', 'edited_at')
    # ### end Alembic commands ###
